package com.exam;
// Generated Mar 22, 2019 1:58:40 AM by Hibernate Tools 4.3.1

import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;





/**
 * Company generated by hbm2java
 */
@ManagedBean
@SessionScoped

public class Company  implements java.io.Serializable {
private List<Company>list;

     private int id;
     private String name;
     private String address;
     private String post;
     private String salary;
     private String vacancy;
     private String password;
     private String contact;

    public Company() {
    }

	
    public Company(int id) {
        this.id = id;
    }
    public Company(int id, String name, String address, String post, String salary, String vacancy, String password, String contact) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.post = post;
       this.salary = salary;
       this.vacancy = vacancy;
       this.password = password;
       this.contact = contact;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    public String getSalary() {
        return this.salary;
    }
    
    public void setSalary(String salary) {
        this.salary = salary;
    }
    public String getVacancy() {
        return this.vacancy;
    }
    
    public void setVacancy(String vacancy) {
        this.vacancy = vacancy;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

public String doSav(){
   CompanyDao ds=new  CompanyDao();
 ds.doSav(this);
 return "companyregister1";

}

public String doUp(){
   CompanyDao ds=new  CompanyDao();
 ds.doUp(this);
 return "companyregister2";

}

public String doDel(){
   CompanyDao ds=new  CompanyDao();
   ds.doDel(this);
   return "companyregister3";
}

    public List<Company> getList() {
        CompanyDao ee = new CompanyDao();
        list=ee.dosh();
        return list;
    }

    public void setList(List<Company> list) {
        this.list = list;
    }






}








