package com.exam;
// Generated Mar 22, 2019 1:58:40 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;




/**
 * Login generated by hbm2java
 */


@ManagedBean
@SessionScoped
public class Login  implements java.io.Serializable {
private List<Login>list=new ArrayList<>();

     private int id;
     private String email;
     private String password;

    public Login() {
    }

	
    public Login(int id) {
        this.id = id;
    }
    public Login(int id, String email, String password) {
       this.id = id;
       this.email = email;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }


public String dosave(){
LoginDao  ds=new LoginDao ();
    ds.dosave(this);
return "Loginp";

}

public String update(){
LoginDao  ds=new LoginDao ();
    ds.update(this);
return "Loginp";

}

public String delete(){
LoginDao  ds=new LoginDao ();
    ds.delete(this);
return "Loginp";

}

    public List<Login> getList() {
        LoginDao  ds=new LoginDao ();
    list=ds.show();
        return list;
    }

    public void setList(List<Login> list) {
        this.list = list;
    }

 public String doShow() {
        String ret = "";
        LoginDao sd = new LoginDao();
        if (sd.aStudent(email, password) != null) {
            ret = "emsuccess";
        } else {

            ret = "up";
        }
        return ret;
    }

}


